---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    pod-security.kubernetes.io/enforce: "baseline"
    pod-security.kubernetes.io/warn: "baseline"
    pod-security.kubernetes.io/audit: "baseline"
